// KASU_APP/resources/js/Pages/Auth/Applicant/ForgotPassword.jsx
import AuthLayout from "@/Layouts/AuthLayout";
import { Head, useForm } from "@inertiajs/react";
import InputField from "@/Components/InputField";
import Button from "@/Components/Button";

function ForgotPassword({ status }) {
    const { data, setData, post, processing, errors } = useForm({
        email: "",
    });

    const submit = (e) => {
        e.preventDefault();
        post(route("password.email"));
    };

    return (
        <>
            <Head title="Forgot Password" />

            <div className="mb-4 text-sm text-gray-600">
                Enter your email address and we’ll send you a link to reset your
                password.
            </div>

            {status && (
                <div className="mb-4 text-sm text-green-600 font-medium">
                    {status}
                </div>
            )}

            <form onSubmit={submit} className="space-y-5">
                {/* EMAIL */}
                <InputField
                    label="Email Address"
                    name="email"
                    type="email"
                    value={data.email}
                    onChange={(e) => setData("email", e.target.value)}
                    error={errors.email}
                    required
                />

                {/* SUBMIT */}
                <Button disabled={processing} className="w-full">
                    Email Password Reset Link
                </Button>
            </form>
        </>
    );
}

ForgotPassword.layout = (page) => (
    <AuthLayout title="Forgot Password">{page}</AuthLayout>
);

export default ForgotPassword;

// educore_sms/resources/js/Pages/Auth/ForgotPassword.vue
<script setup>
    import AuthLayout from '@/Pages/Layouts/AuthLayout.vue';
    import { useForm } from '@inertiajs/vue3';
    import InputField from '../../Components/InputField.vue';
    import Button from '../../Components/Button.vue';

    defineOptions({layout: AuthLayout});

    const form = useForm({
        email: null
    })

    defineProps({
        status: String
    });

</script>

<template>

    <Head title="Forgot password" />
     <div class="bg-gray-100 min-h-screen flex items-center justify-center">

            <div class="w-1/3 mx-auto max-w-5xl bg-white shadow-lg rounded-xl overflow-hidden grid grid-cols-1">
                <div class="flex justify-center">
                    <img src="/public/storage/images/logo_1.png" alt="EduCore SMS" class="h-32">
                </div>
                <div class="space-y-6 px-6 ">
                    <form>
                        <!-- Email -->
                        <InputField
                            type="email"
                            label="Email Address"
                            placeholder="email@example.com"
                            v-model="form.email"
                            :message="form.errors.email"
                        />

                        <Button title="Email password reset link" :disabled="form.processing" />
                    </form>

                    <div class="space-x-1 text-center text-sm text-gray-700 mb-3">
                        <span>Or, return to</span>
                        <Link href="/">log in</Link>
                    </div>
                </div>
            </div>
        </div>
</template>
