// educore_sms/resources/js/Components/Button.vue
<script setup>
defineProps({
    disabled: Boolean,
    loading: Boolean,
});
</script>

<template>
    <div class="my-6 flex items-center justify-start">
        <button
            class="inline-flex items-center justify-center gap-2 w-full rounded-lg px-4 py-2.5 font-medium text-white bg-school-primary transition hover:bg-school-primary-hover disabled:opacity-60 disabled:cursor-not-allowed disabled:hover:bg-school-primary"
        >
            <svg
                v-if="loading"
                class="h-5 w-5 animate-spin"
                viewBox="0 0 24 24"
                fill="none"
            >
                <circle
                    class="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    stroke-width="4"
                />
                <path
                    class="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"
                />
            </svg>
            <slot />
        </button>
    </div>
</template>

<!-- class="mt-3 w-full bg-school-primary hover:bg-school-primary-hover text-white py-2.5 rounded-lg font-medium transition"> -->

// KASU_APP/resources/js/Components/Button.jsx
export default function Button({
    type = 'button',
    disabled = false,
    children,
    fullWidth = false,
    variant = 'primary',
    className = '',
    ...props
}) {
    const baseStyles =
        'inline-flex items-center justify-center rounded-md font-semibold transition focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed'

    const variants = {
        primary:
            'bg-green-700 text-white hover:bg-green-800 focus:ring-green-600',
        secondary:
            'bg-gray-200 text-gray-800 hover:bg-gray-300 focus:ring-gray-400',
        danger:
            'bg-red-600 text-white hover:bg-red-700 focus:ring-red-500',
        outline:
            'border border-green-700 text-green-700 hover:bg-green-50 focus:ring-green-600',
    }

    return (
        <button
            type={type}
            disabled={disabled}
            className={`
                ${baseStyles}
                ${variants[variant]}
                ${fullWidth ? 'w-full' : ''}
                py-2 px-4
                ${className}
            `}
            {...props}
        >
            {children}
        </button>
    )
}
