// KASU_APP/resources/js/Components/InputField.jsx
export default function InputField({
    label,
    name,
    type = 'text',
    value = '',
    onChange,
    error = null,
    required = false,
    placeholder = '',
    disabled = false,
}) {
    const id = `input-${name}`

    return (
        <div className="mb-4">
            <label
                htmlFor={id}
                className="block text-sm font-medium text-gray-700"
            >
                {label}
                {required && <span className="text-red-500 ml-1">*</span>}
            </label>

            <input
                id={id}
                name={name}
                type={type}
                value={value}
                onChange={onChange}
                placeholder={placeholder}
                disabled={disabled}
                aria-invalid={error ? true : false}
                aria-describedby={error ? `${id}-error` : undefined}
                className={`mt-1 block w-full rounded-md border p-2 focus:ring-green-600 focus:border-green-600
                    ${error ? 'border-red-500' : 'border-gray-300'}
                `}
            />

            {error && (
                <p
                    id={`${id}-error`}
                    className="mt-1 text-sm text-red-600"
                >
                    {error}
                </p>
            )}
        </div>
    )
}

// educore_sms/resources/js/Components/InputField.vue
<script setup>
const model = defineModel({
    type: null,
    required: true
});

defineProps({
    label: {
        type: String,
        required: true
    },
    type: {
        type: String,
        required: true,
        default: "text"
    },
    placeholder: {
        type: String
    },
    message: String
});

// const model = defineModel();
</script>

<template>
    <div class="grid gap-1">
        <label class="text-gray-700 text-md">{{label}}</label>
        <input
            v-model="model"
            :type="type"
            :placeholder="placeholder"
            autocomplete="off"
            autofocus
            :class="{'ring-red-400!' : message}"
            :tabindex="2"
            class="text-gray-700 block w-full px-2 py-2 rounded-md border "
        />
        <span class="ml-2 text-red-500" v-if="message">
            {{ message }}
        </span>
    </div>
</template>
