// KASU_APP/resources/js/Components/SelectField.jsx
export default function SelectField({
    label,
    name,
    value = "",
    onChange,
    error = null,
    required = false,
    items,
    valueKey,
    labelKey,
    placeholder,
}) {
    const id = `input-${name}`;

    return (
        <div className="mb-4">
            <label
                htmlFor={id}
                className="block text-sm font-medium text-gray-700"
            >
                {label}
                {required && <span className="text-red-500 ml-1">*</span>}
            </label>

            <select
                value={value}
                onChange={onChange}
                className={`mt-1 block w-full rounded-md border p-2 focus:ring-green-600 focus:border-green-600
                    ${error ? 'border-red-500' : 'border-gray-300'}
                `}
            >
                <option>{placeholder}</option>

                {items.map((item) => (
                    <option key={item[valueKey]} value={item[valueKey]}>
                        {item[labelKey]}
                    </option>
                ))}
            </select>

            {error && (
                <p id={`${id}-error`} className="mt-1 text-sm text-red-600">
                    {error}
                </p>
            )}
        </div>
    );
}

// educore_sms/resources/js/Components/SelectField.vue
<script setup>
const model = defineModel({
    type: null,
    required: true,
});

defineProps({
    items: {
        type: Array,
        required: true,
    },

    label: {
        type: String,
        default: "Select",
    },

    valueKey: {
        type: String,
        default: "id",
    },

    labelKey: {
        type: String,
        default: "name",
    },

    disabled: {
        type: Boolean,
        default: false,
    },

    id: {
        type: String,
        default: null,
    },

    placeholder: {
        type: String,
        default: "-- Select --",
    },
    message: String,
});
</script>

<template>
    <div class="grid gap-1">
        <label v-if="label" :for="id" class="text-gray-700 text-sm font-medium">
            {{ label }}
        </label>
        <select
            :id="id"
            v-model="model"
            :disabled="disabled"
            class="block w-full px-3 py-2 rounded-md border border-gray-300 focus:border-school-primary focus:ring-school-primary disabled:bg-gray-100 disabled:cursor-not-allowed"
        >
            <option value="">{{ placeholder }}</option>

            <option
                v-for="item in items"
                :key="item[valueKey]"
                :value="item[valueKey]"
            >
                {{ item[labelKey] }}
            </option>
        </select>

        <span v-if="message" class="text-sm text-red-500">
            {{ message }}
        </span>
    </div>
</template>
