// educore_sms/resources/js/Pages/Layouts/AuthenticatedLayout.vue
<script setup>
import { ref } from 'vue'
import Sidebar from '@/Components/Sidebar.vue'

defineProps({
    title: {
        type: String,
        default: null,
    },
});

const sidebarOpen = ref(false)
</script>

<template>
    <div class="min-h-screen bg-gray-50 flex">
        <!-- Mobile Overlay -->
        <div v-if="sidebarOpen" class="fixed inset-0 bg-black/40 z-40 md:hidden" @click="sidebarOpen = false" />

        <!-- Sidebar -->
        <Sidebar :sidebarOpen="sidebarOpen" />

        <!-- Main Content -->
        <div class="flex-1 flex flex-col">
            <!-- Topbar -->
            <header class="h-16 bg-white border-b flex items-center justify-between px-4 md:px-6">
                <div class="flex items-center gap-3">
                    <!-- Mobile Menu Button -->
                    <button class="md:hidden text-gray-600" @click="sidebarOpen = true">
                        ☰
                    </button>

                    <h1 class="text-lg font-semibold text-gray-800">
                        {{ title ?? 'Dashboard' }}
                    </h1>
                </div>

                <!-- User -->
                <div class="flex items-center gap-3">
                    <span class="text-sm text-gray-600 hidden sm:block">
                        Admin
                    </span>
                    <div class="h-8 w-8 rounded-full bg-gradient-to-br from-blue-600 to-indigo-600" />
                </div>
            </header>

            <!-- Page -->
            <main class="p-4 sm:p-6 flex-1">

                <slot />
            </main>
        </div>
    </div>
</template>

// KASU_APP/resources/js/Layouts/AuthenticatedLayout.jsx
import AdminSidebar from '@/Components/AdminSidebar'

function AuthenticatedLayout({ user, children }) {
    return (
        <div className="min-h-screen bg-gray-100 flex">
            {/* Sidebar */}
            <AdminSidebar />

            {/* Main content */}
            <div className="flex-1 flex flex-col">
                {/* Top Bar */}
                <header className="bg-white border-b px-6 py-4 flex justify-between items-center">
                    <h1 className="text-lg font-semibold text-gray-800">
                        KASU Admin Portal
                    </h1>

                    <div className="flex items-center gap-4">
                        <span className="text-sm text-gray-600">
                            {user?.name}
                        </span>
                        <form method="post" action={route('admin.logout')}>
                            <button className="text-sm text-red-600 hover:underline">
                                Logout
                            </button>
                        </form>
                    </div>
                </header>

                {/* Page content */}
                <main className="p-6">
                    {children}
                </main>
            </div>
        </div>
    )
}

export default AuthenticatedLayout;
